Feature/tariik mvp/assign developers/ValidationToken
becarselman/ant-colony-pharaoh-backend pull request #25
Opened 2023-06-28 21:04 UTC by TarikVelic

--------------------------------------------------------------------
 MAIN
 * Added employmentType (full-time, part-time)
 * Added token for validation if token exist or not

--------------------------------------------------------------------
 OTHER
 * <other msg> --------------------------------------------------------------------

2023-06-29 11:27 UTC, becarselman requested changes

2023-06-29 11:27 UTC, becarselman commented on app.js
> +// Ruta za provjeru valjanosti tokena
Please use only English

2023-06-29 11:27 UTC, becarselman commented on controllers/validateToken.js
> +  const isValid = tokenService.validateToken(token);
this need to be done in service.

2023-06-29 11:27 UTC, becarselman commented on services/validateToken.js
Idk is this pr wip or you didn't understand your task.

2023-06-29 11:33 UTC, becarselman requested changes

2023-06-29 11:33 UTC, becarselman commented on services/validateToken.js
the point of this task is to check if the jwt is valid or not. This will not help us in solving that problem.

2023-06-30 12:18 UTC, becarselman requested changes

2023-06-30 12:18 UTC, becarselman commented on services/validateToken.js
> +    jwt.verify(token, secretKey);
we can reuse function from utils/helpers that we use in past. And also I this this function will return true and false so we don't need to create condition we just return what ever this function return. But test this

2023-07-03 08:56 UTC, becarselman requested changes

2023-07-03 08:56 UTC, becarselman commented on controllers/validateToken.js
> +  if (isValid) {
this need to be done in service. I think validate token will return true and false so you don't need this condition

2023-07-10 11:28 UTC, AntMarkoLovric approved these changes

2023-07-10 11:37 UTC, closed without merging