FEATURE/ElvaRivle/t5Dxp0AK
becarselman/ant-colony-pharaoh-backend pull request #8
Opened 2023-04-19 19:49 UTC by ElvaRivle

FEATURE/ElvaRivle/t5Dxp0AK

--------------------------------------------------------------------
 MAIN
 * added everything for user registration (route, controller, service, repository)
 * added `password-policy.js` file for settings password rules
--------------------------------------------------------------------
 OTHER
 * performing auto-login upon successful user registration
 * ROLES NOT YET IMPLEMENTED !!!
--------------------------------------------------------------------

2023-04-23 21:16 UTC, ElvaRivle commented
FEATURE/ElvaRivle/t5Dxp0AK

--------------------------------------------------------------------
 MAIN
 * added 2 roles: `User` and `Admin`
 * added validator for roles and password
 * added `role` field to User model
--------------------------------------------------------------------
 OTHER
 * default role, if not specified, is `User`
 * .gitignore for IDE/text editor config files
--------------------------------------------------------------------
 TODO
 * move password hashing to mongoose `pre` middleware 
 * use `joi` to validate request data in middleware
 * maybe implement nicer exception handling, middleware instead of catching in controller?
--------------------------------------------------------------------

2023-04-24 07:59 UTC, becarselman requested changes

2023-04-24 07:59 UTC, becarselman commented on configuration/user-roles.js
> +module.exports = {
You can merge this file and password policy file into one utils/constants file.

2023-04-24 07:59 UTC, becarselman commented on validators/roles.js
> +    for (const key in userRoles) {
You can use "some" function for this. And also you can merge password and roles validatior in one file. utils/validators.js

2023-04-24 07:59 UTC, becarselman commented on repositories/user.js
> +    if (!email) {
I think you are already check this in service. And also we need to care this in service not in repository

2023-04-24 07:59 UTC, becarselman commented on repositories/user.js
> +async function createUser(email, hashedPassword, role) {
Please send this parameters as one object and use it like that.

2023-04-24 07:59 UTC, becarselman commented on services/register.js
> +async function registerUser(email, password, role) {
also we can take here 1 parameter "user". and that parameter will have {email:dlsakfldkasf, password:laksdfjlasfj, role:USER}. I think that is req.body. 
and then you can use it like user.email, user.password...

2023-04-25 20:22 UTC, ElvaRivle commented
FEATURE/ElvaRivle/t5Dxp0AK

--------------------------------------------------------------------
 MAIN
 * added `PORT` and `FRONTEND_URL` env variables
 * allowed CORS for `FRONTEND_URL`
 * send entire `req.body` to service, unpack object there, not in controller
 * removed unnecessary null/undefined checks in repositories and other functions, keep those checks only in service
--------------------------------------------------------------------
 OTHER
 * added `joi` and `cors` packages
 * disabled auto login user upon registration
 * created utils folder and merged validator and constants into single file
 * added `User` role to seeded users
--------------------------------------------------------------------
 TODO
 * use `joi` middleware to validate incoming data 
 * make roles case insensitive
--------------------------------------------------------------------

2023-04-26 13:02 UTC, ElvaRivle commented
FEATURE/ElvaRivle/t5Dxp0AK

--------------------------------------------------------------------
 MAIN
 * created joi validation schemas for request body
 * created register and login middlewares that use joi validation schemas
 * business logic validation kept in services, middleware only does non-business validation
--------------------------------------------------------------------
 OTHER
 * added `joi-password-complexity` package
 * updated password policy object to adhere to password complexity package (renamed object keys)
 * upper-case user roles
--------------------------------------------------------------------

2023-04-26 14:53 UTC, becarselman approved these changes

2023-04-27 20:37 UTC, TarikVelic commented
Great job, LGTM :)

2023-04-27 20:38 UTC, TarikVelic approved these changes
Great job, LGTM :)

2023-04-28 12:04 UTC, merged